### ISSUE TITLE
[FEAT] 쿼리와 검색 결과 일치도 확인 기능 추가

### ISSUE THREAD

**Issue by Ridealist** [teacher-coder/picture-muvie#100]
# 제안 이유
- "모두 다 꽃이야" 동요 검색 시 다른 노래 검색 결과 나옴

# 기대 효과
- 사용자 의도에 맞는 검색 결과 제공

# 할 일
- [ ] 쿼리와 검색 결과 유사도 측정
- [ ] 유사도 높은 결과부터 나오도록 수정

**Comment by hoetaek** [comment]
근데 이게 어떻게 검색해도 안 나오더라고ㅠㅠㅠ
아예 검색 결과에 포함되어 있지 않은듯..?

**Comment by hoetaek** [comment]
네이버 뮤직을 스크래핑할까..?ㅋㅋㅋ
https://cheongpark.tistory.com/m/2
