### ISSUE TITLE
docker settings for deployment

### ISSUE THREAD

**Issue by Ridealist** [teacher-coder/picture-muvie#16]
- AWS EC2에 배포 가능하도록 코드 수정
- 배포용 docker-compose.yml 과 비 배포용 파일 별도 생성

**Comment by hoetaek** [comment]
@Ridealist 이거 해결된거지?

**Comment by Ridealist** [comment]
응 해결된건데 배포 버젼 수정한거 PR을 안 올려서 그때 merge하면서 같이 닫으려 그랬지 @hoetaek

**Comment by hoetaek** [comment]
> 응 해결된건데 배포 버젼 수정한거 PR을 안 올려서 그때 merge하면서 같이 닫으려 그랬지 @hoetaek 

아 아직 안 올린거였구나! 오키
