### ISSUE TITLE
파일 포맷에 대한 유저 선택 UI 제작, 해당 데이터 BE 전달

### ISSUE THREAD

**Issue by Ridealist** [teacher-coder/picture-muvie#29]
# 제안 이유
- hwp, docx 파일 형식간에 호환성 문제
- 별도의 탬플릿 관리 및 제작 후 FE 전송의 필요성

# 기대 효과
- 유저에게 파일 형식에 관계없이 일정한 디자인의 문서 제공 가능

# 구현 결과물 모습 제안
-  ![image](https://user-images.githubusercontent.com/89024993/218346893-cd6185a7-29cb-430a-af18-57e7d71805ba.png)

- request_json = { "file_format" : "hwp", "title" : "이젠 안녕", "lyrics" : ["", "", ...] }

# 할 일
- [ ] FE UI 제작
- [ ] request 필드 추가

**Comment by hoetaek** [comment]
@Ridealist file format은 굳이 BE에 전달 필요 없을듯! frontend에서 다루는 게 여러모로 편할 거 같아~

**Comment by hoetaek** [comment]
이런식으로 구현했어서 코드 가져다 사용하면 되는데 front가 더 편했음!
![image](https://user-images.githubusercontent.com/14107090/218358755-230ae90c-3ecc-4323-a942-406953b84a69.png)
