### ISSUE TITLE
[BUG] docx compose일 때는 hwp 파일이 xml을 제대로 해석하지 못하는 것으로 보임

### ISSUE THREAD

**Issue by hoetaek** [teacher-coder/picture-muvie#34]
# 제안 이유
- 확장자만 달라지는 것으로 한글도 볼 수 있도록 해야 하는데 hwp 파일이 제대로 표시가 안됨
- 아래 스크린샷 참고
![image](https://user-images.githubusercontent.com/14107090/218577879-3ec62fbd-43ce-4c8e-85ed-744ff7e1055c.png)

# 할 일
- [x] docx compose 때문인지 문제 정확하게 파악하기
- [x] docx compose를 사용 안하는 방법으로 구현(subdue 등)

**Comment by Ridealist** [comment]
확인했습니다.
이 문제 때문에 docx compose 대신에 section 쓰는 방법으로 변경했거든. 빨리 PR 올릴게 늦어져서 쏘리쏘리ㅠ

**Comment by hoetaek** [comment]
> 확인했습니다.
> 이 문제 때문에 docx compose 대신에 section 쓰는 방법으로 변경했거든. 빨리 PR 올릴게 늦어져서 쏘리쏘리ㅠ

ㅇㅎ 그럼 이 이슈도 피알에다 연결해줘~

그리고 앞으로 문제 발견하는 것들은 서로 공유하면 좋을 듯!!

**Comment by Ridealist** [comment]
맞어 버그나 오류 있을 때마다 공유하는게 좋겠네~ 확인:)
