### ISSUE TITLE
[BUG] 검색 결과 없거나 500Error 시에도 rotation 이미지 계속 회전

### ISSUE THREAD

**Issue by Ridealist** [teacher-coder/picture-muvie#39]
# 제안 이유
- 검색 결과 없음, 500 Error, broken pipeline 상황에서도 검색 중 rotation 계속 회전 문제
- 검색 결과가 없음에 대한 확실한 정보 제공 필요

# 기대 효과
- 검색 시간 timeout / 오류 상황에 맞는 UI 제공

# 구현 결과물 모습 제안
<img width="520" alt="image" src="https://user-images.githubusercontent.com/89024993/218639738-3d975cb5-6108-4643-99a3-c7420882014c.png">

- 팝업 메세지 / 검색 창에 텍스트 띄우기 등 검색 결과 없음에 대한 명시적 표시
- 검색 결과 없을 때 **'검색' 회전 종료 조건** 추가

# 할 일
- [ ] lyrics json 값을 몇 초 이상 못 받아올 시 오류 메세지창 / 텍스트 표시
- [ ] 검색중 회전 종료 조건 추가

**Comment by hoetaek** [comment]
> # 제안 이유
> 
> - 검색 결과 없음, 500 Error, broken pipeline 상황에서도 검색 중 rotation 계속 회전 문제
> 
> - 검색 결과가 없음에 대한 확실한 정보 제공 필요
> 
> 
> 
> # 기대 효과
> 
> - 검색 시간 timeout / 오류 상황에 맞는 UI 제공
> 
> 
> 
> # 구현 결과물 모습 제안
> 
> <img width="520" alt="image" src="https://user-images.githubusercontent.com/89024993/218639738-3d975cb5-6108-4643-99a3-c7420882014c.png">
> 
> 
> 
> - 팝업 메세지 / 검색 창에 텍스트 띄우기 등 검색 결과 없음에 대한 명시적 표시
> 
> - 검색 결과 없을 때 **'검색' 회전 종료 조건** 추가
> 
> 
> 
> # 할 일
> 
> - [ ] lyrics json 값을 몇 초 이상 못 받아올 시 오류 메세지창 / 텍스트 표시
> 
> - [ ] 검색중 회전 종료 조건 추가
> 
> 

#39 와 duplicate issue 아니지?

**Comment by hoetaek** [comment]
https://github.com/teacher-coder/picture-muvie/pull/32
이걸로 해결되는 문제 같습니다~
