### ISSUE TITLE
[BUG] admin page css rendering

### ISSUE THREAD

**Issue by Ridealist** [teacher-coder/picture-muvie#66]
# 제안 이유
- admin 페이지 css, js 적용 안됨

# 할 일
- [ ] nginx 세팅 확인 -> prod.conf 파일 수정
- [ ] Dockerfile 수정할 부분 확인

**Comment by hoetaek** [comment]
@Ridealist 여기 static 파일들 생성되고 git에서 표시되는데 이거랑 관련된건가??
<img width="336" alt="image" src="https://user-images.githubusercontent.com/14107090/219990050-6f71b275-8dc5-4322-8af1-b68f2e6ec80f.png">

**Comment by Ridealist** [comment]
일단 backlog로 설정~
