### ISSUE TITLE
[IDEA] 구글/네이버 검색창 추가

### ISSUE THREAD

**Issue by Ridealist** [teacher-coder/picture-muvie#78]
# 제안 이유
- '뉴진스' '디토' 처럼 영어를 한글로 검색할 경우 검색이 잘 안되는 문제
- 검색이 안되는 가사에 대해서 편하게 검색할 수 있는 루트 제공

# 기대 효과
- 사용자 경험이 더 좋아짐

# 구현 결과물 모습 제안
![image](https://user-images.githubusercontent.com/89024993/220512463-97657b46-e87c-49fe-842f-c2318a7b4f7a.png)

위 구글 검색창 위치를 '검색' 버튼 아래로 위치히킴
검색 결과가 없을 시 검색창이 뜨도록 코드 수정

# 할 일
- [ ] 아이디어 협의
- [ ] 아이디어 적용

@hoetaek

**Comment by hoetaek** [comment]
@Ridealist 우리가 검색 원하는 결과 안 나오면 여러번 검색해보듯이 ditto 뉴진스로 안 나오면 ditto만 검색해보고 할 듯!
이 이슈는 어제 이야기 나눈걸로 해결한 걸로 하자!

**Comment by Ridealist** [comment]
응 지금의 UI가 훨씬 좋다. 검색창 필요 없겠어~ @hoetaek
